language: node_js

node_js:
  - "node"

env:
  - workerCount=2 timeout=600000

branches:
  only:
    - dev
    - master

install:
  - yarn install

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn link && yarn link @candlelib/test && tsc -p ./tsconfig.json && yarn test
