import { CSSNodeType } from "./node_type.js";

export enum CSSNodeTypeLU {
    Stylesheet = CSSNodeType.Stylesheet,
    Rule = CSSNodeType.Rule,
    Import = CSSNodeType.Import,
    Keyframes = CSSNodeType.Keyframes,
    KeyframeBlock = CSSNodeType.KeyframeBlock,
    KeyframeSelector = CSSNodeType.KeyframeSelector,
    SupportConditions = CSSNodeType.SupportConditions,
    Supports = CSSNodeType.Supports,
    Not = CSSNodeType.Not,
    And = CSSNodeType.And,
    Or = CSSNodeType.Or,
    Parenthesis = CSSNodeType.Parenthesis,
    Function = CSSNodeType.Function,
    MediaQueries = CSSNodeType.MediaQueries,
    Media = CSSNodeType.Media,
    Query = CSSNodeType.Query,
    MediaFeature = CSSNodeType.MediaFeature,
    MediaFunction = CSSNodeType.MediaFunction,
    MediaValue = CSSNodeType.MediaValue,
    MediaType = CSSNodeType.MediaType,
    MediaEquality = CSSNodeType.MediaEquality,
    MediaRangeAscending = CSSNodeType.MediaRangeAscending,
    MediaRangeDescending = CSSNodeType.MediaRangeDescending,
    ComboSelector = CSSNodeType.ComboSelector,
    ComplexSelector = CSSNodeType.ComplexSelector,
    PseudoSelector = CSSNodeType.PseudoSelector,
    CompoundSelector = CSSNodeType.CompoundSelector,
    TypeSelector = CSSNodeType.TypeSelector,
    MetaSelector = CSSNodeType.MetaSelector,
    NamespacePrefix = CSSNodeType.NamespacePrefix,
    QualifiedName = CSSNodeType.QualifiedName,
    IdSelector = CSSNodeType.IdSelector,
    ClassSelector = CSSNodeType.ClassSelector,
    AttributeSelector = CSSNodeType.AttributeSelector,
    PseudoClassSelector = CSSNodeType.PseudoClassSelector,
    PseudoElementSelector = CSSNodeType.PseudoElementSelector,
    KeyframeSelectors = CSSNodeType.KeyframeSelectors,
    Combinator = CSSNodeType.Combinator,
    A_SPECIFIER = CSSNodeType.A_SPECIFIER,
    B_SPECIFIER = CSSNodeType.B_SPECIFIER,
    C_SPECIFIER = CSSNodeType.C_SPECIFIER,
    D_SPECIFIER = CSSNodeType.D_SPECIFIER
}

